### ISSUE TITLE
Request: React demo

### ISSUE THREAD

**Issue by joshwcomeau** [foxbenjaminfox/meteor-loading#1]
In the README, you mention that this package is more flexible than `sacha:spin` because it's not tied to a specific templating system.

I'm having trouble understand how, exactly, I would use this with React though. I see lots of neat configuration options, and the API looks great, but I'm still unclear how the initial render happens.

Would very much appreciate a quick start-to-end "using with React" demo!

Thanks :smile:

**Comment by foxbenjaminfox** [comment]
Awesome, I'm glad you like it! The reason this is more flexible than `sacha:spin` is that `sacha:spin` bundles theunderlying `spin.js` npm package into a Blaze template, whereas my package dosmt have a dependency on Blaze. In both packages, the underlying API of `spin.js` gets used, appending the element of the spinner to the DOM. Now, the way `sacha:spin` does it involves a Blaze template that includes a container div for `spin.js` to render the spinner into. This gives you control over where in the DOM to render the spinner. But because it is absolutely positioned, this doesn't matter. It spins in the screens center regardless.

So this package abstracts over all that, and just uses `spin.js` to append the spinner to the DOM. (It ends up at the end of the body.) This allows ever so slightly less flexibility, but it makes the API a fair bit nicer, and makes the package rendering-system agonistic. (Which is a major advantage, as it allows the package to work with e.g. React.)

Basicly, because all this runs outside the React root element, it and React should ignore each other completely, and coexist in perfect harmony.

So in practice, you can use it in a React-based site in _exactly_ the same way as from a Blaze-based site. This package doesn't care one bit.

However, now that you've pointed it out, I realize that this is a hole in the package's test covarage. While I don't think React examples are even meaningful (you will note that the examples in the README don't depend on Blaze or on the rendering engine at all), I now realize that some tests of the package with React could be a good idea, to ensure that nothing breaks with React. There is no reason why it should be problematic, but test covarage is always a good thing.

Of course, you could also use such tests as a reference to see how it is done, although the way it is done doesn't differ in the slightest: this package's API is pure Javascript.

I'll certainly add those tests. But try it out! Try some of the examples from the README, and it should just work! If you have any questions, or comments, or are struggling to get it working and need some help, or whatever, feel free to ask.

**Comment by joshwcomeau** [comment]
Thanks for the detailed response! That makes total sense; I wasn't aware that it worked outside of the templating context and just appended to the body. Smart way to do that!

I will certainly give that a go, thanks again =)
