### ISSUE TITLE
matching HTML?

### ISSUE THREAD

**Issue by tewksbum** [foxbenjaminfox/meteor-loading#2]
Hi,

Not to be dense, but do you have any examples of the matching .HTML that goes with this?

Thanks!

**Comment by foxbenjaminfox** [comment]
You're not the first to be confused by this, so don't feel so bad. Perhaps
the documentation could be improved some how to make this more obvious.

This package doesn't require you to write any additional HTML at all. It's
got the simplest interface possible: you add it to your project (with
`meteor add`), and then in your javascript you've got access to the
`Loading` object, on which you can call a bunch of methods, as documented
in the README. Start it, stop it, call Meteor methods through it, and so
forth. Then it Just Works. The spinner appears and disappears as your code
commands.

This module takes care of all DOM stuff, no hand-rolled HTML needed. The
philosophy is that you shouldn't need to care about all of that. All you
need to do is tell it when to start and stop. (Of course, it's fully
configurable, so you can also customize how the spinner will look, if you
want. (As described in the README.))

I hope this makes it all clear. Feel free to ask if there's anything you
feel is still unclear.

**Comment by tewksbum** [comment]
Thanks Ben!  I really appreciate the response!

Two follow-up questions:
1. Default positioning = body... I think I kind of understand this... but
   that can be repositioned to: elementSelector: '#someId'?
2. And in terms of the wrapping functions
   (Loading.wrapAsync(someAsyncFunction);)
3. thoughts / examples when used w/ "instance" & template level subscription
   stuff?

Thanks again!
- Marcus

**Comment by foxbenjaminfox** [comment]
1) Right. If you pass in the elementSelector option, the spinner element will be created inside the element specified by the selector. (Instead of being a child of the body element.)

Be careful with this! If you remove the parent element, you remove the spinner. That isn't a problem usually, but if for example you make it be a child of an element inside a Blaze `{{#if}}` whose condition becomes false and then immediately true again, that element will disappear and reappear, but the spinner will be gone.

2) The `.wrapAsync` method wasn't really designed with subscriptions in mind. The use case was supposed to be when you are using some library for something (with an async interface), and you want to show a loading indicator while that is running.

With top level subscriptions, you could do `Loading.wrapAsync(Meteor.subscribe, Meteor)` to get a subscription function that shows a spinner until it is ready, as `Meteor.subscribe` can be passed a function as its last argument that will be treated as an `onReady` callback. But the instance level subscribe function only takes an object as that argument (with `onReady`, `onStop`, and `connection` attributes.)

Adding subscription support to this library would be fairly easy, and it could be a good addition. I'll find time to do it, that is unless you want to send a pull request? This is a good and easy task to get started with contributing to open source, if you want.

If you don't that's fine too. I'll add it the next time I get around to it. For now though, you can write code like this:

``` javascript
Loading.start();
instance.subscribe('subscription', {
    onReady () {
        Loading.stop();
    }
});
```

It's a bit more verbose, but that's why this library has the `.start`/`.stop` API. Even in use-cases I didn't think of and didn't write wrappers for, you can always use it that way.

I wrote wrappers for Meteor methods, and for generic async functions that take a callback as their last argument, but I didn't write a wrapper for Meteor subscriptions. You're right that that would be convenient, and indeed that's a thing that (now that you mentioned it), will probably end up in the next version of this package.

I'm glad you're getting good use out of my package, and again, feel free to ask if anything is still unclear.
